-- TẠO DATABASE MASTER KEY
USE MASTER
GO

SELECT * FROM SYS.SYMMETRIC_KEYS
IF NOT EXISTS (SELECT * FROM SYS.SYMMETRIC_KEYS WHERE NAME LIKE '%MS_DatabaseMasterKey##')
BEGIN
	CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'YourStrongPassword123'
END
GO

-- TẠO CERTIFICATE DÙNG ĐỂ MÃ HÓA/GIẢI MÃ DATABASE ENCRYPTION KEY (DEK)
CREATE CERTIFICATE TDE_CERT_CHATPIGEONS
WITH SUBJECT = 'Cert ma hoa cho ChatPigeons'
GO

-- TẠO DEK BÊN TRONG DATABASE CHATPIGEONS
USE ChatPigeons
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE TDE_CERT_CHATPIGEONS
GO

-- BẬT MÃ HÓA DỮ LIỆU
ALTER DATABASE ChatPigeons SET ENCRYPTION ON
GO

-- KIỂM TRA TRẠNG THÁI MÃ HÓA
SELECT DB_NAME(DATABASE_ID) AS DATABASENAME, 
    ENCRYPTION_STATE, 
    CASE ENCRYPTION_STATE
        WHEN 1 THEN 'Unencrypted'
        WHEN 2 THEN 'Encryption in progress'
        WHEN 3 THEN 'Encrypted' 
    END AS STATUS
FROM SYS.DM_DATABASE_ENCRYPTION_KEYS
GO

-- BACKUP CERTIFICATE
USE MASTER
GO

BACKUP CERTIFICATE TDE_CERT_CHATPIGEONS
TO FILE = 'D:\TDE_Cert_ChatPigeons.cer'
WITH PRIVATE KEY (
    FILE = 'D:\TDE_Cert_ChatPigeons.pvk',
    ENCRYPTION BY PASSWORD = 'YourStrongPassword123'
)